### PR TITLE
WIP: build verification on Travis CI

### PR DESCRIPTION
**Pull request by kiritigowda**
Gitlab-CI related files removed.

Travis CI YML added.

API-Docs module not added as submodule by default, YML file brings the api-docs for headers. Link below has the build

https://travis-ci.org/kiritigowda/OpenVX-sample-impl

### CODE REVIEW

**Comment by kiritigowda** [comment]
Khronos travis - https://travis-ci.org/kiritigowda/OpenVX-sample-impl

**Comment by oddhack** [comment]
It's desirable to keep the gitlab and github repositories consistent, so unless the WG wants to stop running CI on internal citlab checkins, keeping the gitlab CI file is advisable.

**Comment by kiritigowda** [comment]
That would be good, I will revert the gitlab-ci file.

**Comment by kiritigowda** [comment]
closing this pull request and added a new one without gitlab-ci changes.

**Pull request closed without merging**
