### PR TITLE
MulticoreWare Khronos OpenVX_1_3 Raspberry PI 3 B+ Project

### PR DESCRIPTION
**Pull request by zhaodongmcw**
Please review absdiff kernel of NEON intrinsics to merge into branch OpenVX1.3.

### CODE REVIEW

**Comment by zhaodongmcw** [comment]
Please review colorconvert, nonlinearfilter, phase and threshold kernels of NEON intrinsics to merge into branch OpenVX1.3.

**Comment by zhaodongmcw** [comment]
Add 34 kernels of NEON intrinsics

**Comment by zhaodongmcw** [comment]
Add the rest kernels of NEON intrinsics

**Comment by zhaodongmcw** [comment]
Fix the bug that some kernels do not have image remainder computation

**Comment by zhaodongmcw** [comment]
Fix the bug that Harris_Score calling C reference

**Comment by zhaodongmcw** [comment]
We do not have access to the "api-docs" repo, you should add :

VX_KERNEL_WEIGHTED_AVERAGE = VX_KERNEL_BASE(VX_ID_KHRONOS, VX_LIBRARY_KHR_BASE) + 0x40,
in "include/VX/vx_kernels.h"

VX_API_ENTRY vx_node VX_API_CALL vxWeightedAverageImageNode(vx_graph graph, 
                        vx_image img1, 
                        vx_scalar alpha, 
                        vx_image img2, 
                        vx_image output);
in "include/VX/vx_nodes.h"

VX_API_ENTRY vx_status VX_API_CALL vxuWeightedAverageImage(vx_context context, vx_image img1, vx_scalar alpha, vx_image img2, vx_image output);
in "include/VX/vxu.h"

**Comment by zhaodongmcw** [comment]
As per Implement the OpenVX 1.3 Adopter's program, we implement vxQueryMetaFormatAttribute and delay object(tensor, object array), please check.

**Comment by zhaodongmcw** [comment]
Implement vxGetUserStructNameByEnum, vxCreateTensorFromHandle, vxSwapTensorHandle, vxMapTensorPatch and vxUnmapTensorPatch, please check.

By the way, we try to use with ifdefs OPENVX_CONFORMANCE_VISION to filter kernel absdiff, please check if it is the result expected by khronos.

**Comment by zhaodongmcw** [comment]
Add feature set flags to Concerto makefiles:
OPENVX_CONFORMANCE_VISION
OPENVX_CONFORMANCE_NEURAL_NETWORKS
OPENVX_CONFORMANCE_VISION_NNEF_IMPORT
OPENVX_USE_ENHANCED_VISION

Please check.

**Comment by kiritigowda** [comment]
@zhaodongmcw the OpenVX 1.3 headers are available on GitHub API Docs project. The 1.3 headers are on the openvx_1.3 branch, which you can use to build the sample implementation.
https://github.com/KhronosGroup/OpenVX-api-docs/tree/openvx_1.3

**Comment by kiritigowda** [comment]
Closing this pull request as the commits are done in GitLab

**Pull request closed without merging**
